# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0351997b9c38e9b07433e121c555fc78fa62432bd6ad8a715249e6c4f2b2026587738f338aac133f0c1f52665fe7344c37f00f2078d077a06c5e017518290a17

test:
  secret_key_base: 1dc07ad77be2172b0087b23e073b3f730e38ee9839d4cf5380c39c35fdc233abede1f66467d870afd25191a12acbfef8b601fe7fa16e5076a96d421f2da33468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
